### ISSUE TITLE
deep recursion in Mojo::JSON from swagger api file with many $ref's

### ISSUE THREAD

**Issue by stephenhoward** [jhthorsen/mojolicious-plugin-openapi#46] opened 2017-08-15 23:18 UTC
The following gist includes a small test case using Mojolicious::Plugin::OpenAPI.  When visiting the base_path (/v1) the plugin attempts to serve the api spec, as documented.  The html documentation renders fine, but the json version hangs on deep recursion.  The swagger.io api editor tells me the included yaml swagger file contains no errors.  It seems that Mojo::JSON's naive traversal of the resulting perl structure is at fault:

https://gist.github.com/stephenhoward/20e599e4bcc8c7cf6458ccba53e29bb0

**Comment by mrenvoize** [comment] 2017-08-16 05:55
I can confirm this one, thanks for the test case.

**Comment by jhthorsen** [comment] 2017-08-16 08:44
Thanks for reporting in.

Could you try to make the test case smaller? And if possible, could you rewrite your test to something like https://github.com/jhthorsen/mojolicious-plugin-openapi/blob/master/t/validate.t ? The YAML specification can just be placed in the \_\_DATA__ section.

**Comment by stephenhoward** [comment] 2017-08-16 14:31
Here is a test file that replicates the deep recursion issue:

https://gist.github.com/stephenhoward/35351db0837ec64b649482b5ccb66c16

**Comment by mrenvoize** [comment] 2017-08-21 20:13
This is a duplicate of #39 I think. That issue links to some code for inspiration on how.we may fix the problem but unfortunately I've not had the time to pursue it.

_Sent from my Sony D5803 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by stephenhoward** [comment] 2017-09-03 15:13
This patch (across 2 projects) solves the recursion issue. It marks all expanded $refs with a _ref key that Mojo::JSON uses to restore the original $ref on dump.

    diff --git a/lib/Mojo/JSON.pm b/lib/Mojo/JSON.pm
    index be16aaf21..4be9d67c8 100644
    --- a/lib/Mojo/JSON.pm
    +++ b/lib/Mojo/JSON.pm
    @@ -212,6 +212,10 @@ sub _encode_array {
     
     sub _encode_object {
       my $object = shift;
    +
    +  return _encode_string('$ref') . ':' . _encode_value($object->{_ref} )
    +      if ( $object->{_ref} );
    +
       my @pairs = map { _encode_string($_) . ':' . _encode_value($object->{$_}) }
         sort keys %$object;
       return '{' . join(',', @pairs) . '}';
       
    diff --git a/lib/JSON/Validator.pm b/lib/JSON/Validator.pm
    index fd120d8..3f24746 100644
    --- a/lib/JSON/Validator.pm
    +++ b/lib/JSON/Validator.pm
    @@ -293,21 +293,22 @@ sub _resolver {
       for my $topic (@$refs) {
         my $ref = delete $topic->{'$ref'} or next;    # already resolved?
         $ref = "#/definitions/$ref" if $ref =~ /^\w+$/;    # TODO: Figure out if this could be removed
    -    $ref = Mojo::Util::url_unescape($ref || '');
    -    $ref = Mojo::URL->new($namespace)->fragment($ref) if $ref =~ s!^\#!!;
    -    $ref = Mojo::URL->new($ref) unless ref $ref;
    +    my $uri = Mojo::Util::url_unescape($ref || '');
    +    $uri = Mojo::URL->new($namespace)->fragment($uri) if $uri =~ s!^\#!!;
    +    $uri = Mojo::URL->new($uri) unless ref $uri;
     
    -    my $look_in = $self->_store(resolved => $ref);
    +    my $look_in = $self->_store(resolved => $uri);
         if (!$look_in) {
    -      $look_in = $self->_load_schema($ref, $namespace);
    +      $look_in = $self->_load_schema($uri, $namespace);
           $look_in = $self->_resolve_schema($look_in, $look_in->data->{id} || $namespace);
         }
     
    -    warn "[JSON::Validator] Resolving $ref\n" if DEBUG > 1;
    -    warn Data::Dumper::Dumper($look_in->data) if DEBUG and $ref =~ /\b[c]\b/;   # follow the changes
    -    my $data = $ref->fragment ? $look_in->get($ref->fragment) : $look_in->data;
    -    die qq[Possibly a typo in schema? Could not find "$ref"] unless $data;
    +    warn "[JSON::Validator] Resolving $uri\n" if DEBUG > 1;
    +    warn Data::Dumper::Dumper($look_in->data) if DEBUG and $uri =~ /\b[c]\b/;   # follow the changes
    +    my $data = $uri->fragment ? $look_in->get($uri->fragment) : $look_in->data;
    +    die qq[Possibly a typo in schema? Could not find "$uri"] unless $data;
         $topic->{$_} = $data->{$_} for keys %$data;
    +    $topic->{_ref} = $ref;
         unshift @$refs, $topic if $topic->{'$ref'} and !ref $topic->{'$ref'};
         delete $topic->{id} if !ref $topic->{id} and $self->isa('JSON::Validator::OpenAPI');
       }
    @@ -631,7 +632,9 @@ sub _validate_type_object {
         # Special case used internally when validating schemas: This module adds "id"
         # on the top level which might conflict with very strict schemas, so we have to
         # remove it again unless there's a rule.
    -    local $rules{id} = 1 if !$path and exists $data->{id};
    +    # It also adds "_ref" to track $ref links, and must be handled similarly.
    +    local $rules{id}   = 1 if !$path and exists $data->{id};
    +    local $rules{_ref} = 1 if exists $data->{_ref};
     
         if (my @keys = grep { !$rules{$_} } keys %$data) {
           local $" = ', ';

**Comment by mrenvoize** [comment] 2017-09-15 15:04
Sorry, I hadn't spotted this earlier @stephenhoward , I'll try to take a look and come up with a way forward.  Looks fairly sensible to me.

**Comment by jhthorsen** [comment] 2017-09-16 07:47
@stephenhoward: Your patch for Mojo::JSON will not happen.

I appreciate the job you've done on the patch. It's very helpful.

**Comment by mrenvoize** [comment] 2017-09-18 07:43
At a cursory glance, it looks to me like we could use this new ref tracker code to construct a 'bundle' method as suggested in #39. Which uses the self-referential object in `data` and the $ref hash to reconstruct the plain structure (with JSON Schema $ref's included) to pass to Mojo::JSON (or whatever your preference JSON encoder is) to encode as a JSON string.

**Comment by stephenhoward** [comment] 2017-09-18 16:24
It might make the most sense to add the method that re-inserts the '$ref' key-value pairs in JSON::Validator, and then call that method from Mojolicious::Plugin::OpenAPI before feeding the results into Mojo::JSON, so that all of the ref-related magic stays in one module.

**Comment by jhthorsen** [comment] 2017-09-25 16:46
Maybe we could merge all the remote documents into one big local document and then resolve $refs on the fly when validating... I'm not sure if this is a good idea though.

**Comment by jhthorsen** [comment] 2017-10-10 19:23
I just opened https://github.com/jhthorsen/json-validator/pull/79. Can you try it out?

**Comment by jhthorsen** [comment] 2017-10-22 18:20
Pretty sure this is fixed now, with the new release of JSON::Validator.

**Closed by jhthorsen** 2017-10-22 18:20 UTC
Labels: bug
